services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    env_file:
      - ./env/.env.local
    volumes:
      - .:/app
      - /app/bin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
