services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:8080"
    env_file:
      - ./env/.env.prod
    volumes: []
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
    healthcheck:
      test: ["CMD", "/main", "--health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
