# This workflow will build a Go project
# For more information, ref: https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-go

name: Infra API CI using Golang

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
concurrency:
  group: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || format('push-{0}', github.sha) }}
  cancel-in-progress: true
  
jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      
      - name: Build with Go
        run: echo 'building with go lol'
